name: 'Alpine Semantic Releaser'
description: 'Run semantic-release on a repo'
branding:
  color: purple
  icon: box
inputs:
  github-token:
    description: 'Github token for pushing releases'
    required: true
    default: ''
  plugins:
    description: 'Space separated semantic-release plugins to install'
    required: false
    default: ''
runs:
  using: 'docker'
  image: docker://rdaniels6813/semantic-release-alpine
  entrypoint: '/main.sh'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    PLUGINS: ${{ inputs.plugins }}
